import { Inter } from "next/font/google";
import "./globals.scss";
import "./responsive-manager.scss";
import "animate.css/animate.min.css";
import { CartContextProvider } from "@/store/cart-context";
import { UserContextProvider } from "@/store/user-context";
import { FavouriteContextProvider } from "@/store/fav-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <FavouriteContextProvider>
            <CartContextProvider>
              <main>{children}</main>
            </CartContextProvider>
          </FavouriteContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
